### ISSUE TITLE
Javascript Example

### ISSUE THREAD

**Issue by marcgilgien** [admin-ch/CovidCertificate-Api-Scripts#3]
I would probably remove Roger Federer from the javascript example JSON

**Comment by foxxycodes** [comment]
> I would probably remove Roger Federer from the javascript example JSON

What do you have against Roger?

**Comment by marcgilgien** [comment]
> > I would probably remove Roger Federer from the javascript example JSON
> 
> 
> 
> What do you have against Roger?

Absolutely nothing :) I just wanted to point out that there is a real life name in an example and it would probably better to use something more generic. Not everybody agrees to having his name used in a public example, even if it's Roger.

**Comment by delixfe** [comment]
Fixed in cecfe7b558b006de3a0c34d0e65f91254e643913.
